// Stage 3/4 production checklist. These prompts exercise live retrieval and
// grounded-answer review in the manager-only console.
export const AI_RETRIEVAL_EVALUATION_SET = Object.freeze([
  "How does scoring freeze work?", "What does NR mean?", "What is the Reliability Factor requirement?", "What happens if a player gets injured and can't finish?", "How does Picklebreaker work?", "When does Match Setup need to be completed?", "How do I complete Match Setup in the LMS?", "How many players play in the Weekday league?", "How does the Saturday league work?", "Who chooses serve or receive?", "How many timeouts does each team get?", "What behavior is expected if a player is verbally abusive?", "Where do I find my player information in the LMS?", "How does a captain manage a lineup in the LMS?", "How does an administrator update league information?", "What does Rule 4.5 say?", "What is the club policy on weather cancellations?",
  "Someone got hurt halfway through the game. What do we do?", "Someone got hurt halfway through the game and can't finish. What do we do?", "How early do captains have to put their players in?", "Can somebody swear at another player during a match?", "Where do I put my lineup?", "Why does my rating say NR?", "How does Picklebraker work?", "What is the Reliabilty Factor?", "How do I record a forfeiture?", "Where is Match Setp?",
  "How early do we have to submit Match Setup?", "What's the deadline for Match Setup?", "How many days before the match is Match Setup due?", "Where do I enter my Match Setup?", "What button do I use to save Match Setup?", "How do I change my Match Setup lineup?", "When are match scores due?", "How do I enter match scores?",
  "What type of balls will we be using?", "How do I complete Match Setup in the LMS?", "How does a Picklebreaker work?", "What happens if a player is verbally abusive to another player?", "Can I yell at or insult another player during a match?", "Can I yell at another player?", "Can I insult another player?", "What happens if someone is verbally abusive?", "Is trash talking allowed?", "Can someone swear at an opponent?", "What are the sportsmanship rules?", "What happens if a player is disrespectful?", "Can I throw my paddle when I'm angry?", "Can I make an aggressive serve?",
  "When do I need to enter my match lineup?", "When is my match lineup due?", "How do I enter my match lineup?", "When do I enter my lineup and how do I do it?", "When do captains submit their roster?", "When does Match Setup need to be completed?", "How do I complete Match Setup in the LMS?", "When do I enter my match linup?", "How do I complete Match Setp?", "What is the lineup for tonight?", "Who is in my lineup?", "Can I change the batting lineup?", "What does setup mean outside of league match setup?",
]);
