"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {roleLabel} from "../../lib/permissions";
import {APP_VERSION} from "../../lib/version";
import styles from "../page.module.css";
import adminStyles from "./admin.module.css";

const paths={dashboard:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,people:<><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M17 7a3 3 0 0 1 0 6m-1 2a5 5 0 0 1 5 5"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4m8-4v4M3 10h18"/></>,structure:<><circle cx="12" cy="5" r="2"/><circle cx="5" cy="18" r="2"/><circle cx="19" cy="18" r="2"/><path d="M12 7v4M5 16v-3h14v3"/></>,document:<><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6m-6 4h6"/></>,modules:<><rect x="3" y="3" width="8" height="8" rx="2"/><rect x="13" y="3" width="8" height="8" rx="2"/><rect x="3" y="13" width="8" height="8" rx="2"/><path d="M17 14v6m-3-3h6"/></>,help:<><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.3 2.3 0 1 1 3.7 1.8c-1 .7-1.5 1.2-1.5 2.7m0 3.5h.01"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,logout:<><path d="M10 4H5v16h5m4-4 4-4-4-4m4 4H9"/></>};
function Icon({name,size=20}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function name(m){return [m?.first_name,m?.last_name].filter(Boolean).join(" ").trim()||m?.full_name||m?.email||"Administrator"}
function initials(m){return name(m).split(/\s+/).slice(0,2).map((x)=>x[0]?.toUpperCase()).join("")||"AD"}
function profilePhotoUrl(person){const urls=Array.isArray(person?.profile_image_urls)?person.profile_image_urls:[];return urls.find((url)=>String(url).includes("/storage/v1/object/public/profile-photos/"))||""}
function AdminAvatar({member}){const imageUrl=profilePhotoUrl(member),[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[imageUrl]);return <span className={[styles.avatar,styles.userAvatar,styles.blue].join(" ")}>{imageUrl&&!failed?<Image src={imageUrl} width={80} height={80} alt={name(member)+" profile"} onError={()=>setFailed(true)} unoptimized/>:initials(member)}</span>}
function value(v,d=0){const n=Number(v);return v!==null&&v!==undefined&&v!==""&&Number.isFinite(n)?n.toFixed(d):"--"}
function ScopeOptions({data={}}){return <><option value="active">Active Seasons</option><option value="current">Not Active (Current Entries)</option><option value="all">All Seasons</option><optgroup label="Seasons">{(data.seasons||[]).map((x)=><option key={x.id} value={"season:"+x.id}>{x.name}</option>)}</optgroup><optgroup label="Leagues">{(data.leagues||[]).map((x)=><option key={x.id} value={"league:"+x.id}>{x.name}</option>)}</optgroup><optgroup label="Divisions">{(data.divisions||[]).map((x)=><option key={x.id} value={"division:"+x.id}>{x.name}</option>)}</optgroup></>}

export default function AdminDesignPreviewView({dashboard={}}){
 const member=dashboard.member||{},counts=dashboard.counts||{},year=new Date().getFullYear(),sections=[...(dashboard.sections||[]),dashboard.moduleSection].filter(Boolean);
 const [active,setActive]=useState("dashboard"),[expanded,setExpanded]=useState(""),[dialog,setDialog]=useState(""),[profile,setProfile]=useState(false),[logoutOpen,setLogoutOpen]=useState(false),[loggingOut,setLoggingOut]=useState(false);
 const metrics=[["Active Members",value(counts.members),"Current club members","blue"],["Players on Teams",value(counts.playersOnTeamsUnique),"Unique rostered players","green"],["Teams",value(counts.teams),"Selected-scope teams","navy"],["Matches This Week",value(counts.matchesThisWeek),"Scheduled match days","gold"]];
 const statuses=[["Pending Verification",value(counts.pendingVerification),"Scores awaiting review",Number(counts.pendingVerification||0)>0],["Matches Played",value(counts.matchesPlayed),"Verified match days"],["Games Played",value(counts.gamesPlayed),"Verified game scores"],["Average Team DUPR",value(counts.averageTeamDupr,3),"Average roster rating"]];
 useEffect(()=>{const close=(e)=>{if(e.key==="Escape"){setDialog("");setProfile(false);setLogoutOpen(false)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
 function go(key){setActive(key);setExpanded("");document.getElementById("admin-preview-"+key)?.scrollIntoView({behavior:"smooth",block:"start"})}
 function nav(key,label,icon,onClick,expandable=false){return <button type="button" className={active===key?styles.active:""} aria-expanded={expandable?expanded===key:undefined} onClick={onClick||(()=>go(key))}><Icon name={icon}/><span><b>{label}</b></span></button>}
 function groupedNav(key,label,icon){const section=sections.find((item)=>item.key===key),cards=section?.cards||[];return <div className={styles.navGroup}>{nav(key,label,icon,()=>{setActive(key);setExpanded((current)=>current===key?"":key)},true)}{expanded===key&&<div className={styles.submenu}>{cards.map((card)=><button type="button" key={card.title} onClick={()=>{setExpanded("");if(card.dialog)setDialog(card.dialog);else dashboard.onNavigate?.(card.path)}}><span>{card.title}</span></button>)}</div>}</div>}
 function openDialog(key){setActive(key);setExpanded("");setDialog(key)}
 async function logout(){setLoggingOut(true);try{await dashboard.onLogout?.()}catch(error){setLoggingOut(false);alert(error?.message||"Unable to log out.")}}
 return <main className={["full-screen-main",styles.page,adminStyles.adminPage].join(" ")}>
  <aside className={styles.sidebar}><a className={styles.brand} href="https://lwrpickleballclub.com" target="_blank" rel="noreferrer"><Image src="/lms-icon-192.png" width={46} height={46} alt="Lakewood Ranch Pickleball Club" priority/><strong>Lakewood Ranch Pickleball Club</strong></a><nav className={styles.sideNav}><div className={styles.navGroup}>{nav("dashboard","Dashboard","dashboard",()=>{setActive("dashboard");setExpanded((current)=>current==="dashboard"?"":"dashboard")},true)}{expanded==="dashboard"&&<div className={styles.submenu}><button type="button" onClick={()=>dashboard.onChangeDashboard?.("/design-preview")}><span>Player Dashboard</span></button><button type="button" onClick={()=>dashboard.onChangeDashboard?.("/design-preview/captain")}><span>Captain Dashboard</span></button><button type="button" className={styles.submenuActive} aria-current="page" onClick={()=>go("dashboard")}><span>Admin Dashboard</span></button></div>}</div>{nav("analytics","League Analytics","structure")}{groupedNav("people","People & Teams","people")}{groupedNav("matches","Match Operations","calendar")}{groupedNav("structure","League Structure","structure")}{groupedNav("system","System Setup","structure")}{nav("guides","Dashboard Guides","document",()=>openDialog("guides"))}{nav("messages","Dashboard Messages","document",()=>openDialog("messages"))}{groupedNav("modules","Modules","modules")}</nav><div className={styles.season}><span>Selected scope</span><strong>{dashboard.scopeLabel||"Active Seasons"}</strong><small>Admin operations</small></div><p className={styles.sidebarCopyright}>&copy; {year} Lakewood Ranch Pickleball Club</p></aside>
  <section className={styles.content}>
   <header className={styles.desktopHeader}><div><span>Admin dashboard</span><h1>Welcome, {member.first_name||name(member).split(" ")[0]}</h1></div><div className={styles.headerActions}><button type="button" className={styles.helpButton} onClick={()=>dashboard.onOpenGuide?.()}><Icon name="help"/></button><div className={styles.userIdentity}><strong>{name(member)}</strong><small>{roleLabel(dashboard.role)}</small></div><button type="button" className={styles.profileButton} onClick={()=>setProfile(true)}><AdminAvatar member={member}/></button></div></header>
   <header className={styles.mobileHeader}><a className={styles.mobileLogo} href="https://lwrpickleballclub.com" target="_blank" rel="noreferrer"><Image src="/lms-icon-192.png" width={36} height={36} alt=""/></a><div className={styles.mobileTitle}><strong>Admin Dashboard</strong><span>{dashboard.scopeLabel||"Active Seasons"}</span></div><div className={styles.mobileActions}><button type="button" onClick={()=>dashboard.onOpenGuide?.()}><Icon name="help" size={18}/></button><button type="button" onClick={()=>setProfile(true)}><AdminAvatar member={member}/></button></div></header>
   <label className={[styles.mobileDashboardSelect,adminStyles.mobileScope].join(" ")}><span>Dashboard Scope</span><select value={dashboard.filter||"active"} onChange={(e)=>dashboard.onSelectFilter?.(e.target.value)}><ScopeOptions data={dashboard.filterOptions}/></select></label>
   <section className={adminStyles.snapshot} id="admin-preview-dashboard"><header><div><span>System Snapshot</span><h2>Club Operational Overview</h2><p>League health, participation, scheduling, and scoring for the selected scope.</p></div><label><span>Dashboard Scope</span><select value={dashboard.filter||"active"} onChange={(e)=>dashboard.onSelectFilter?.(e.target.value)}><ScopeOptions data={dashboard.filterOptions}/></select></label></header><div className={adminStyles.metrics}>{metrics.map(([label,count,helper,tone])=><article className={adminStyles[tone]} key={label}><span>{label}</span><strong>{count}</strong><small>{helper}</small></article>)}</div><div className={adminStyles.statuses}>{statuses.map(([label,count,helper,alert])=><button type="button" className={alert?adminStyles.alert:""} key={label} onClick={()=>alert&&dashboard.onNavigate?.("/scoring")}><span>{label}</span><strong>{count}</strong><small>{helper}</small></button>)}</div></section>
   <div className={adminStyles.stack}>{dashboard.analyticsPanel&&<section className={adminStyles.analytics} id="admin-preview-analytics">{dashboard.analyticsPanel}</section>}{sections.map((section,index)=>{const key=section.key||(index===0?"people":index===1?"matches":index===2?"structure":"modules");return <section className={adminStyles.tools} id={"admin-preview-"+key} key={section.title}><header><div><span>{key==="modules"?"Connected tools":"Administration"}</span><h2>{section.title}</h2><p>{section.desc}</p></div><strong>{section.cards.length} Tools</strong></header><div>{section.cards.map((card)=><button type="button" key={card.path} onClick={()=>card.dialog?openDialog(card.dialog):dashboard.onNavigate?.(card.path)}><b className={adminStyles[card.tone]}>{card.code}</b><span><strong>{card.title}</strong><small>{card.desc}</small></span><Icon name="arrow" size={17}/></button>)}</div></section>})}
    <section className={adminStyles.next} id="admin-preview-guides"><div><span>Dashboard administration</span><h2>Dashboard Guides</h2><p>Select the PDF guides shown on the Player, Captain, and Admin dashboards.</p></div><button type="button" onClick={()=>openDialog("guides")}>Manage Guides <Icon name="arrow" size={17}/></button></section>
    <section className={adminStyles.next} id="admin-preview-messages"><div><span>Dashboard administration</span><h2>Dashboard Messages</h2><p>Create login messages and review the existing message history.</p></div><button type="button" onClick={()=>openDialog("messages")}>Manage Messages <Icon name="arrow" size={17}/></button></section>
   </div><p className={styles.note}>Live Admin dashboard - current permissions, scope filters, counts, and navigation</p><p className={styles.mobileCopyright}>&copy; {year} Lakewood Ranch Pickleball Club</p>
  </section>
  <nav className={styles.bottomNav}>{[["dashboard","Dashboard","dashboard"],["people","People","people"],["matches","Matches","calendar"],["structure","Structure","structure"],["modules","Modules","modules"]].map(([key,label,icon])=><button type="button" className={active===key?styles.active:""} key={key} onClick={()=>go(key)}><Icon name={icon} size={20}/><span>{label}</span></button>)}</nav>
  {dialog&&<div className={styles.modalLayer} role="dialog" aria-modal="true" aria-labelledby="admin-panel-dialog-title"><button type="button" className={styles.backdrop} onClick={()=>setDialog("")} aria-label="Close admin panel"/><section className={adminStyles.adminDialog}><header><div><span>Admin Dashboard</span><h2 id="admin-panel-dialog-title">{dialog==="guides"?"Dashboard Guides":dialog==="messages"?"Dashboard Messages":"System Reset Options"}</h2></div><button type="button" onClick={()=>setDialog("")} aria-label="Close admin panel">&times;</button></header><div className={adminStyles.dialogBody}>{dialog==="guides"?dashboard.guidesPanel:dialog==="messages"?dashboard.messagesPanel:dashboard.resetPanel}</div></section></div>}
  {dashboard.resetHelpPanel}
  {profile&&<div className={styles.modalLayer} role="dialog" aria-modal="true"><button type="button" className={styles.backdrop} onClick={()=>setProfile(false)}/><section className={styles.profileDialog}><header><AdminAvatar member={member}/><div><span>Signed-in profile</span><h2>{name(member)}</h2><p>{roleLabel(dashboard.role)}{member.email?" - "+member.email:""}</p></div><button type="button" onClick={()=>setProfile(false)}>&times;</button></header><div className={styles.profileActions}><Link href="/reset-password?returnTo=%2Fdesign-preview%2Fadmin" onClick={()=>setProfile(false)}><Icon name="help"/><span><strong>Change Password</strong><small>Update this account</small></span><Icon name="arrow" size={17}/></Link><Link href="/design-preview" onClick={()=>setProfile(false)}><Icon name="dashboard"/><span><strong>Player Dashboard</strong><small>Open redesigned player view</small></span><Icon name="arrow" size={17}/></Link><Link href="/design-preview/captain" onClick={()=>setProfile(false)}><Icon name="dashboard"/><span><strong>Captain Dashboard</strong><small>Open redesigned captain view</small></span><Icon name="arrow" size={17}/></Link><button type="button" className={styles.logoutAction} onClick={()=>setLogoutOpen(true)}><Icon name="logout"/><span><strong>Log Out</strong><small>This browser or device only</small></span><Icon name="arrow" size={17}/></button></div><footer className={styles.profileMeta}><span>Version {APP_VERSION}</span><span>&copy; {year} Lakewood Ranch Pickleball Club</span></footer></section></div>}
  {logoutOpen&&<div className={[styles.modalLayer,styles.confirmLayer].join(" ")}><button type="button" className={styles.backdrop} onClick={()=>!loggingOut&&setLogoutOpen(false)}/><section className={styles.confirmDialog}><span>Account</span><h2>Log out of this device?</h2><p>You will remain signed in elsewhere.</p><div><button type="button" onClick={()=>setLogoutOpen(false)}>Stay signed in</button><button type="button" className={styles.confirmLogout} onClick={logout}>{loggingOut?"Logging out...":"Log out"}</button></div></section></div>}
 </main>
}