import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {eligibilityIntent,needsEligibility} from '../app/lib/aiEligibilityIntent.js';
import {displayQuestionForSubmission} from '../app/lib/askLwrAssistantConfig.js';
import {openLive,sealLive} from '../app/lib/liveLmsReceipts.js';
import {eligibilityPolicy,evaluateEligibility,divisionOptions,rfClassification,classifyRfCondition} from '../app/lib/aiEligibilityPolicy.js';
import {runEligibility} from '../app/lib/aiEligibilityService.js';
import {catalog,candidates,divisions,sourceDatabase} from './helpers/eligibilityFixture.mjs';
import {id} from './helpers/viewAsFixture.mjs';
process.env.SUPABASE_SERVICE_ROLE_KEY='local-synthetic-eligibility-fixture-only';
const division=divisionOptions(divisions,eligibilityIntent('Can I play DUPR5?'))[0];const policy=eligibilityPolicy(candidates,division);
export const controls=[
 ['RF01 below', {rf:28,value:4,sourceIsNr:false},'NR','PARTIALLY_CONFIRMED'],
 ['RF02 fraction', {rf:28.999,value:4,sourceIsNr:false},'NR','PARTIALLY_CONFIRMED'],
 ['RF03 boundary', {rf:29,value:2.8,sourceIsNr:false},'NR','PARTIALLY_CONFIRMED'],
 ['RF04 above', {rf:80,value:2.8,sourceIsNr:false},'RATED','PARTIALLY_CONFIRMED'],
 ['RF05 missing', {rf:null,value:2.8,sourceIsNr:false},'RF_UNKNOWN','CANNOT_DETERMINE'],
 ['RF06 numeric NR', {rf:20,value:4,sourceIsNr:true},'NR','PARTIALLY_CONFIRMED'],
 ['RF07 rated below', {rf:80,value:1.9,sourceIsNr:false},'RATED','NOT_ELIGIBLE'],
 ['RF08 rated inside', {rf:80,value:2.899,sourceIsNr:false},'RATED','PARTIALLY_CONFIRMED'],
 ['RF09 rated above', {rf:80,value:2.9,sourceIsNr:false},'RATED','NOT_ELIGIBLE'],
 ['RF10 independent NR', {rf:80,value:4,sourceIsNr:true},'NR','PARTIALLY_CONFIRMED'],
 ['RF11 independent unknown', {rf:80,value:2.8,sourceIsNr:null},'RF_UNKNOWN','CANNOT_DETERMINE'],
 ['RF12 pair unknown', {rf:80,value:2.5,sourceIsNr:false},'RATED','PARTIALLY_CONFIRMED'],
];
for(const [label,input,classification,outcome] of controls)test(label,()=>{assert.equal(policy.status,'READY');const r=evaluateEligibility(policy,input);assert.equal(r.classification,classification);assert.equal(r.outcome,outcome);assert.ok(r.unresolved.includes('PAIR_AGGREGATE_UNKNOWN'));});
const principal={user:{id:id(101)},receiptBinding:'synthetic-session',supabase:sourceDatabase()};
async function ask(question,extra={}){let calls=0,telemetry=[];const r=await runEligibility({body:{question},principal,loadCatalog:async()=>catalog,lookup:async q=>{calls++;assert.equal(q.subjectKind,'SELF');return {data:{status:'success',rf:28.999,value:4,sourceIsNr:false}};},persist:async(_db,make)=>{telemetry.push(make());return true;},...extra});return {r,calls,telemetry};}
test('Exact official source gate + NR precedence + sanitized single telemetry outcome',async()=>{const {r,calls,telemetry}=await ask('Can I play DUPR5?');assert.equal(r.kind,'answer');assert.equal(calls,1);assert.equal(r.eligibility.classification,'NR');assert.equal(r.sources.length,1);assert.equal(r.eligibility.evidence.length,8);assert.match(r.answer,/minus 0.5/);assert.doesNotMatch(r.answer,/28.999/);assert.equal(telemetry.length,1);assert.doesNotMatch(JSON.stringify(telemetry),/28.999|sourceIsNr|reliability|member_id/);});
test('Policy only never reads SELF',async()=>{const {r,calls}=await ask('What are the requirements for DUPR5?');assert.equal(r.kind,'answer');assert.equal(calls,0);assert.equal(r.eligibility.outcome,'POLICY_ONLY');});
test('PT9 conflict blocks personal lookup; no crossing to Weekday rules',async()=>{const {r,calls}=await ask('Can I play PrimeTime 9?');assert.equal(r.kind,'conflict');assert.equal(calls,0);assert.equal(r.eligibility.outcome,'POLICY_CONFIGURATION_CONFLICT');});
test('PrimeTime age policy includes exact 6.3.2 source; no live lookup',async()=>{const {r,calls}=await ask('What age do I need to be for PrimeTime?');assert.equal(r.kind,'answer');assert.match(r.answer,/12\/31/);assert.equal(calls,0);});
test('Clarification binds subject session, exact choice and current source',async()=>{const {r,calls}=await ask('Can I play DUPR7?');assert.equal(r.kind,'clarification');assert.equal(calls,0);const body={question:r.clarification.options[0].key,conversationReceipt:r.conversationReceipt};const continued=(await ask('',{body})).r;assert.equal(continued.kind,'answer');assert.match(continued.resolvedQuestion,/Can I play DUPR7\?.*2026 Fall Season/);assert.doesNotMatch(continued.resolvedQuestion,/choice:/);assert.equal((await ask('',{body,principal:{...principal,receiptBinding:'other'}})).r.kind,'technical_error');assert.equal((await ask('',{body:{...body,question:'choice:forged'}})).r.kind,'technical_error');assert.equal((await ask('',{body,loadCatalog:async()=>({...catalog,candidates:candidates.map(c=>({...c,documentVersionId:id(900)}))})})).r.kind,'insufficient_evidence');});
test('Inactive or unavailable SDUPR5 does not substitute another division',async()=>{const {r,calls}=await ask('Can I play SDUPR5?');assert.equal(r.eligibility.outcome,'CANNOT_DETERMINE');assert.equal(calls,0);assert.deepEqual(r.sources,[]);});
test('Missing RF stays unknown and denied subject remains protected',async()=>{assert.equal((await ask('Can I play DUPR5?',{lookup:async()=>({data:{status:'missing',rf:null,value:2.8}})})).r.eligibility.outcome,'CANNOT_DETERMINE');assert.equal((await ask('Can I play DUPR5?',{lookup:async()=>({data:{status:'denied'}})})).r.kind,'protected');});
test('Telemetry exceptions fail open with exactly one logical attempt',async()=>{let n=0;const {r}=await ask('Can I play DUPR5?',{persist:async()=>{n++;throw Error('synthetic');}});assert.equal(r.kind,'answer');assert.equal(n,1);});
test('Standalone other-player RF is protected before catalog or provider',async()=>{for(const q of ["What is John's RF?",'What is my Reliability Factor?']){const {r,calls}=await ask(q,{loadCatalog:async()=>{throw Error('must not read');}});assert.equal(r.kind,'protected');assert.equal(calls,0);}});
test('Changed policy version, future season and missing continuation fail closed',()=>{assert.equal(eligibilityPolicy(candidates,{...division,seasonId:id(999)}).status,'POLICY_SCOPE_UNKNOWN');assert.equal(eligibilityPolicy(candidates.filter(c=>!/^4\.5\.1\./m.test(c.content)),division).status,'POLICY_UNKNOWN');assert.equal(rfClassification(29,policy),'NR');});
const reportedQuestion='If I have a player who is 3.6 in DUPR but reliability less than 29%, does the NR rule apply';
const activeVersion=id(901);
const currentCandidates=candidates.map(c=>({...c,documentVersionId:activeVersion,content:c.content.replace('Reliability Factor of 29 or below','Reliability Score/Factor of 29 or below').replace('5.6. Roster Requirements','5.7. Roster Requirements')}));
const activeCatalog={rulesVersionId:activeVersion,candidates:currentCandidates,divisions};
const syntheticSources=async(_db,evidence)=>evidence.map(e=>({documentId:e.documentId,documentVersionId:e.documentVersionId,chunkId:e.chunkId,documentTitle:e.documentTitle,pageNumber:e.pageNumber}));
const activeOptions={loadCatalog:async()=>activeCatalog,resolveSources:syntheticSources};
test('Reported RF/NR question uses current Rule 4.1.1 directly, without division or player lookup',async()=>{const intent=eligibilityIntent(reportedQuestion);assert.deepEqual(intent.rfCondition,{operator:'lt',value:'29'});assert.equal(intent.decimal,'3.6');assert.equal(intent.kind,'source_rf_policy');const {r,calls}=await ask(reportedQuestion,activeOptions);assert.equal(r.kind,'answer');assert.equal(calls,0);assert.equal(r.eligibility.classification,'NR');assert.match(r.answer,/Yes.*Rule 4\.1\.1/s);assert.match(r.answer,/3\.6/);assert.match(r.answer,/not a check of that player's stored rating/);assert.equal(r.sources.length,1);assert.match(r.sources[0].citation,/Rules pages/);});
test('Sourced RF threshold handles below, boundary and above without a hardcoded number',async()=>{for(const [operator,value,classification] of [['eq','28','NR'],['eq','29','NR'],['eq','30','RATED'],['lt','29','NR'],['gt','29','RATED_BY_RF']])assert.equal(classifyRfCondition({operator,value},29),classification);const changedCandidates=currentCandidates.map(c=>({...c,content:c.content.replace('Score/Factor of 29 or below','Score/Factor of 31 or below')}));const changedCatalog={...activeCatalog,candidates:changedCandidates};const {r,calls}=await ask('Does the NR rule apply if reliability is 30?',{...activeOptions,loadCatalog:async()=>changedCatalog});assert.equal(r.kind,'answer');assert.equal(calls,0);assert.equal(r.eligibility.classification,'NR');assert.match(r.answer,/31-or-below/);});
test('RF condition parser retains inclusive wording and strict comparisons',()=>{assert.deepEqual(eligibilityIntent('Does the NR rule apply with Reliability Score/Factor of 29 or below?').rfCondition,{operator:'lte',value:'29'});assert.deepEqual(eligibilityIntent('Does the NR rule apply with reliability less than 29%?').rfCondition,{operator:'lt',value:'29'});assert.deepEqual(eligibilityIntent('Does the NR rule apply with RF greater than 29?').rfCondition,{operator:'gt',value:'29'});assert.equal(eligibilityIntent('RF is 28.5, what happens?').decimal,null);});
test('Missing, stale and changed Rules evidence fail as insufficient evidence',async()=>{const missing=currentCandidates.filter(c=>!c.content.includes('4.1.1.'));assert.equal((await ask(reportedQuestion,{...activeOptions,loadCatalog:async()=>({...activeCatalog,candidates:missing})})).r.kind,'insufficient_evidence');const changed=currentCandidates.map(c=>({...c,content:c.content.replace('or below will be classified as','or less should be classified as')}));assert.equal((await ask(reportedQuestion,{...activeOptions,loadCatalog:async()=>({...activeCatalog,candidates:changed})})).r.kind,'insufficient_evidence');assert.equal((await ask(reportedQuestion,{...activeOptions,loadCatalog:async()=>({...activeCatalog,rulesVersionId:id(902)})})).r.kind,'insufficient_evidence');const noAssignment=currentCandidates.filter(c=>!/^4\.5\.1\./m.test(c.content));assert.equal((await ask('What are the requirements for a player with reliability less than 29% and DUPR 3.6?',{...activeOptions,loadCatalog:async()=>({...activeCatalog,candidates:noAssignment})})).r.kind,'insufficient_evidence');});
test('Reliability condition and original question survive signed clarification receipt',async()=>{const question='What are the requirements for a player with reliability less than 29% and DUPR 3.6?';const intent=eligibilityIntent(question);assert.equal(intent.number,null);assert.deepEqual(intent.rfCondition,{operator:'lt',value:'29'});const first=(await ask(question,activeOptions)).r;assert.equal(first.kind,'clarification');const second=(await ask('',{...activeOptions,body:{question:first.clarification.options[0].key,conversationReceipt:first.conversationReceipt}})).r;assert.equal(second.kind,'answer');assert.match(second.resolvedQuestion,/reliability less than 29%/);assert.match(second.answer,/reliability condition in your question falls within the 29-or-below NR rule/);assert.doesNotMatch(second.resolvedQuestion,/choice:/);});
test('Expired, forged, cross-user and receiptless eligibility choices fail closed',async()=>{const first=(await ask('Can I play DUPR7?',activeOptions)).r;const question=first.clarification.options[0].key;const receipt=first.conversationReceipt;const body={question,conversationReceipt:receipt};const payload=openLive('live1.'+receipt.slice('live1.eligibility.'.length),'eligibility',principal);const expired='live1.eligibility.'+sealLive('eligibility',principal,payload,Date.now()-300001).slice(6);assert.equal((await ask('',{...activeOptions,body:{question,conversationReceipt:expired}})).r.kind,'technical_error');assert.equal((await ask('',{...activeOptions,body,principal:{...principal,user:{id:id(102)}}})).r.kind,'technical_error');assert.equal((await ask('',{...activeOptions,body:{...body,question:'choice:forged'}})).r.kind,'technical_error');assert.equal(needsEligibility({question}),true);assert.equal((await ask('',{...activeOptions,body:{question}})).r.kind,'technical_error');});
test('Component choice contract reaches the eligibility route and signed receipt continuation',async()=>{const [choices,assistant,route]=await Promise.all(['../app/components/AskLwrChoices.js','../app/components/AskLwrAssistant.js','../app/api/ask-lwr/route.js'].map(path=>readFile(new URL(path,import.meta.url),'utf8')));assert.match(choices,/onChoose\(option\.key,option\.label\)/);assert.match(assistant,/displayQuestionForSubmission\(nextQuestion,choiceLabel\)/);assert.match(assistant,/JSON\.stringify\(\{ question: nextQuestion, conversationReceipt/);assert.match(route,/if\(needsEligibility\(body\)\)/);assert.match(route,/runEligibility\(\{body,principal:await authenticateLive\(req\)/);const question='What are the requirements for a player with reliability less than 29% and DUPR 3.6?';const first=(await ask(question,activeOptions)).r;assert.equal(first.kind,'clarification');const selected=first.clarification.options[0];const body={question:selected.key,conversationReceipt:first.conversationReceipt};assert.equal(needsEligibility(body),true);assert.equal(displayQuestionForSubmission(body.question,selected.label),selected.label);assert.doesNotMatch(displayQuestionForSubmission(body.question),/choice:/);const receipt=openLive('live1.'+first.conversationReceipt.slice('live1.eligibility.'.length),'eligibility',principal);assert.equal(receipt.originalQuestion,question);assert.deepEqual(receipt.intent.rfCondition,{operator:'lt',value:'29'});const {r,calls}=await ask('',{...activeOptions,body});assert.equal(calls,0);assert.equal(r.kind,'answer');assert.match(r.resolvedQuestion,/reliability less than 29%/);assert.match(r.answer,/29-or-below NR rule/);});
