import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';
import {createViewAsProjectionClient} from '../app/lib/viewAsProjectionClient.js';
const source=(await readFile(new URL('../app/lib/auth.js',import.meta.url),'utf8')).replace(/^import .*;\r?$/gm,'').replace(/export /g,'');
function authHarness(mode,roleName="captain",authSource=source){let created=0,authCalls=0;const session={user:{id:'normal-user',email:'normal@example.invalid'},access_token:'synthetic-normal-token'};const client={auth:{getSession:async()=>{authCalls++;return{data:{session}};},getUser:async()=>{authCalls++;return{data:{user:session.user}};}}};const scope={process:{env:{}},createClient:()=>{created++;return client;},isViewAsMode:()=>mode,getViewAsPageState:()=>({viewer:{role:'captain',memberId:'target-member'}}),viewAsDisplayClient:{},viewAsSelfRows:()=>({data:[{id:'target-member'}],error:null,user:null}),findMembersByEmail:async(c,email,selection)=>({data:[{id:'normal-member',email,selection}]}),memberEmailResolution:rows=>({activeMembers:rows,selectedMember:rows?.[0]}),highestRoleForMembers:()=>roleName,hasRole:()=>true,defaultDashboardForRole:()=>'/player-dashboard',alert:()=>{}};vm.createContext(scope);vm.runInContext(authSource+'\nglobalThis.api={getCurrentMemberRows,getCurrentUserRole,requireRole,getRequestAuthorizationHeaders};',scope);return {api:scope.api,created:()=>created,authCalls:()=>authCalls};}
test('0726 normal member/role/auth headers preserve normal identity without View-As state',async()=>{const h=authHarness(false);assert.equal(h.created(),1);assert.equal((await h.api.getCurrentMemberRows('id,email')).data[0].id,'normal-member');assert.equal((await h.api.getCurrentUserRole()).memberId,'normal-member');assert.equal((await h.api.getRequestAuthorizationHeaders()).Authorization,'Bearer synthetic-normal-token');assert.equal((await h.api.requireRole({push(){throw new Error('unexpected redirect');}},'captain')).memberId,'normal-member');assert.equal(h.authCalls(),4);});
test('0726 isolated identity creates no Supabase client or target Auth session',async()=>{const h=authHarness(true);assert.equal(h.created(),0);const role=await h.api.getCurrentUserRole();assert.equal(role.memberId,'target-member');assert.equal(role.session,null);assert.equal((await h.api.getCurrentMemberRows('*')).data[0].id,'target-member');assert.equal((await h.api.requireRole({push(){throw new Error('unexpected redirect');}},'captain')).memberId,'target-member');assert.equal(h.authCalls(),0);});
test('0726 in-memory projection reuses joins and filters but cannot fetch or mutate',async()=>{let available=true;const c=createViewAsProjectionClient(()=>available?{teams:[{id:'t',home_location_id:'l',captain_member_id:'m'}],members:[{id:'m',first_name:'Target'}],locations:[{id:'l',name:'Court'}],team_members:[{id:'tm',team_id:'t',member_id:'m'}]}:null);const q=await c.from('team_members').select('id,members(id,first_name),teams (id,locations (name),captain:members!teams_captain_member_id_fkey(first_name))').eq('team_id','t');assert.equal(q.data[0].teams.locations.name,'Court');assert.equal(q.data[0].teams.captain.first_name,'Target');for(const op of ['insert','update','delete','upsert'])assert.ok((await c.from('teams')[op]({name:'forged'})).error);assert.equal((await c.auth.getSession()).data.session,null);assert.ok((await c.from('secrets').select('*')).error);available=false;assert.ok((await c.from('teams').select('*')).error);});

test('0726 normal authentication matches the recovered baseline for all five role levels',async()=>{
 const original=(await readFile(new URL('./fixtures/lms0726-normal-auth-baseline.txt',import.meta.url),'utf8')).replace(/^import .*;\r?$/gm,'').replace(/export /g,'')+'\nasync function getCurrentMemberRows(){}';
 for(const role of ['player','captain','club_pro','league_manager','commissioner']){const before=authHarness(false,role,original),after=authHarness(false,role);assert.equal(JSON.stringify(await after.api.getCurrentUserRole()),JSON.stringify(await before.api.getCurrentUserRole()));assert.equal(JSON.stringify(await after.api.getRequestAuthorizationHeaders()),JSON.stringify(await before.api.getRequestAuthorizationHeaders()));assert.equal(after.created(),before.created());}
});

test('0726 keeps one real LMS presentation and removes the mini snapshot transport',async()=>{
 const entry=await readFile(new URL('../app/view-as/page.js',import.meta.url),'utf8');assert.match(entry,/return null/);assert.doesNotMatch(entry,/AskLwr|snapshot|<section|<nav/);
 const transport=await readFile(new URL('../app/api/view-as/read/route.js',import.meta.url),'utf8');assert.doesNotMatch(transport,/operation==='snapshot'/);
 const provider=await readFile(new URL('../app/components/ViewAsSharedPages.js',import.meta.url),'utf8');assert.match(provider,/<Fragment key={revision}>{children}<\/Fragment>/);assert.doesNotMatch(provider,/resultSourcePresentation|<table|<textarea/);
});

test('0726 shared settings loader preserves normal fetch and uses only projected values in View-As',async()=>{
 const code=(await readFile(new URL('../app/lib/viewAsPageState.js',import.meta.url),'utf8')).replace(/^import .*;\r?$/gm,'').replace(/export /g,'');
 let calls=0;const normalResponse={synthetic:true};const scope={document:{documentElement:{dataset:{}}},fetch:async url=>{assert.equal(url,'/api/system-settings');calls++;return normalResponse;},Response,URL,createConversationContext:()=>({reset(){}}),createViewAsProjectionClient:()=>({})};vm.createContext(scope);vm.runInContext(code+'\nglobalThis.api={displaySystemSettings,setViewAsPageState};',scope);
 assert.equal(await scope.api.displaySystemSettings(),normalResponse);assert.equal(calls,1);scope.document.documentElement.dataset.lmsViewAs='true';scope.api.setViewAsPageState({viewer:{memberId:'target'},tables:{system_settings:[{setting_key:'club_name',setting_value:'Synthetic Club'}]}});assert.deepEqual(await(await scope.api.displaySystemSettings()).json(),{success:true,settings:{club_name:'Synthetic Club'}});assert.equal(calls,1);
});
