import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { sendEmailMessages } from "../../lib/notifications";
import { hasRole } from "../../lib/permissions";
export const runtime = "nodejs";
const audienceLabels={all_members:"All Active Members",players:"Players in Scope",captains:"Captains & Club Pros in Scope"};
function db(service=false){const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=service?(process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY):process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Supabase credentials are not configured.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function manager(req){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const {data}=await db().auth.getUser(token);if(!data?.user?.email)return{error:"Not authorized.",status:401};const supabase=db(true),{data:member,error}=await supabase.from("members").select("id,email,user_roles(role)").eq("email",data.user.email).maybeSingle();if(error)throw error;if(!hasRole(member?.user_roles?.[0]?.role||"player","league_manager"))return{error:"Only League Managers and Commissioners can use League Communications.",status:403};return{supabase,member}}
async function options(s){const [a,b,c]=await Promise.all([s.from("seasons").select("id,name").order("name"),s.from("leagues").select("id,name,season_id,seasons(name)").order("name"),s.from("divisions").select("id,name,league_id,leagues(season_id,seasons(is_active,start_date,end_date))").order("name")]);if(a.error||b.error||c.error)throw a.error||b.error||c.error;return{seasons:a.data||[],leagues:b.data||[],divisions:c.data||[]}}
function matches(scope,d){if(scope==="all")return true;if(scope.startsWith("division:"))return d.id===scope.slice(9);if(scope.startsWith("league:"))return d.league_id===scope.slice(7);if(scope.startsWith("season:"))return d.leagues?.season_id===scope.slice(7);const x=d.leagues?.seasons,today=new Date().toISOString().slice(0,10),active=Boolean(x?.is_active)&&(!x.start_date||x.start_date<=today)&&(!x.end_date||x.end_date>=today);return scope==="active"?active:!active}
async function emails(s,a,scope){if(a==="all_members"&&scope==="all"){const{data,error}=await s.from("members").select("email").eq("is_active_member",true).not("email","is",null);if(error)throw error;return unique(data)}const o=await options(s),ids=o.divisions.filter(d=>matches(scope,d)).map(d=>d.id);if(!ids.length)return[];const{data:teams,error}=await s.from("teams").select("id,captain_member_id,co_captain_member_id,co_captain_2_member_id,club_pro_member_id").in("division_id",ids).eq("is_active",true);if(error)throw error;let memberIds=[];if(a==="captains")memberIds=(teams||[]).flatMap(t=>[t.captain_member_id,t.co_captain_member_id,t.co_captain_2_member_id,t.club_pro_member_id]).filter(Boolean);else{const teamIds=(teams||[]).map(t=>t.id);if(!teamIds.length)return[];const r=await s.from("team_members").select("member_id").in("team_id",teamIds);if(r.error)throw r.error;memberIds=(r.data||[]).map(x=>x.member_id)}if(!memberIds.length)return[];const r=await s.from("members").select("email").in("id",[...new Set(memberIds)]).eq("is_active_member",true).not("email","is",null);if(r.error)throw r.error;return unique(r.data)}
function unique(rows=[]){return[...new Set(rows.map(x=>String(x.email||"").trim().toLowerCase()).filter(Boolean))]}
export async function GET(req){try{const a=await manager(req);if(a.error)return NextResponse.json({success:false,error:a.error},{status:a.status});const u=new URL(req.url);if(u.searchParams.get("history")==="true"){const r=await a.supabase.from("league_communication_history").select("id,audience,scope,subject,body,attachment_names,recipient_count,sent_count,status,sent_by_email,created_at").order("created_at",{ascending:false}).limit(100);if(r.error)throw r.error;return NextResponse.json({success:true,history:r.data||[]})}const audience=u.searchParams.get("audience")||"players",scope=u.searchParams.get("scope")||"active",[count,scopeOptions]=await Promise.all([emails(a.supabase,audience,scope),options(a.supabase)]);return NextResponse.json({success:true,recipientCount:count.length,scopeOptions})}catch(error){return NextResponse.json({success:false,error:error.message},{status:500})}}
export async function POST(req){try{const a=await manager(req);if(a.error)return NextResponse.json({success:false,error:a.error},{status:a.status});const{audience="players",scope="active",subject,html,text,attachments=[]}=await req.json(),to=await emails(a.supabase,audience,scope),safeAttachments=Array.isArray(attachments)?attachments.filter(item=>item?.name&&item?.content).slice(0,1):[];if(!subject?.trim()||(!html?.trim()&&!text?.trim()))return NextResponse.json({success:false,error:"Enter a subject and email body."},{status:400});if(safeAttachments.some(item=>String(item.content).length>4000000))return NextResponse.json({success:false,error:"Choose an attachment smaller than 3 MB."},{status:400});if(!to.length)return NextResponse.json({success:false,error:"No active email recipients match this selection."},{status:400});const sent=await sendEmailMessages({emails:to,subject:subject.trim(),html,text,attachments:safeAttachments}),sentCount=Number(sent.sent||0),r=await a.supabase.from("league_communication_history").insert({audience:audienceLabels[audience]||audience,scope,subject:subject.trim(),body:html||text,attachment_names:safeAttachments.map(item=>String(item.name)),recipient_count:to.length,sent_count:sentCount,status:sentCount===to.length?"sent":"failed",sent_by_member_id:a.member?.id,sent_by_email:a.member?.email});if(r.error)throw r.error;if(sentCount!==to.length)return NextResponse.json({success:false,error:sent.reason||"Email delivery failed."},{status:502});return NextResponse.json({success:true,sentCount,recipientCount:to.length})}catch(error){return NextResponse.json({success:false,error:error.message},{status:500})}}
