'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {getRequestAuthorizationHeaders} from '../../lib/auth';
import {APPROVED_SCOPES,clubPolicyDate} from '../../lib/aiApprovedAnswersShared.js';
import {RETEST_KEY} from '../../lib/aiReviewShared.js';
import styles from './review.module.css';
import approvedStyles from './approved.module.css';
import ExistingEvidenceDecision from './ExistingEvidenceDecision.js';
async function approvedApi(params={},body){const r=await fetch(`/api/ai-assistant/approved-answers?${new URLSearchParams(params)}`,{method:body?'POST':'GET',cache:'no-store',headers:{...(await getRequestAuthorizationHeaders()),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Approved Answers unavailable.');return result;}
const date=v=>v?new Date(v).toLocaleString(undefined,{timeZoneName:'short'}):'Not recorded';
const blank=()=>({title:'',topic_key:'',canonical_question:'',approved_answer:'',league_scope:'all',temporal_scope:'standing',season_id:null,effective_on:clubPolicyDate(),expires_on:null,related_chunk_id:null,related_passage:null,related_rule_identity:null,public_links:[]});
export default function ApprovedAnswersPanel({initialCaseId,router,request=approvedApi}){
 const api=request;
 const [data,setData]=useState({revisions:[],seasons:[],warnings:[]}),[error,setError]=useState(''),[detail,setDetail]=useState(null),[caseData,setCaseData]=useState(null),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[scope,setScope]=useState(''),[source,setSource]=useState(null);
 const load=useCallback(async()=>{try{setData(await api());}catch(e){setError(e.message);}},[api]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{if(!initialCaseId)return;let active=true;(async()=>{try{const c=await api({op:'case',id:initialCaseId});if(active)setCaseData(c);}catch(e){if(active)setError(e.message);}})();return()=>{active=false;};},[initialCaseId,api]);
 async function open(id){setBusy(true);setError('');try{setDetail(await api({op:'detail',id}));setCaseData(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function viewSource(id){try{setSource((await api({op:'source',id})).source);}catch(e){setError(e.message);}}
 function retest(question){try{sessionStorage.setItem(RETEST_KEY,JSON.stringify({question,expires:Date.now()+300000}));router.push('/ai-assistant/console');}catch{setError('Unable to prefill. Copy the question into Test AI Assistant.');}}
 return <section className={approvedStyles.panel} aria-label="Approved Answers"><h2>Approved Answers</h2><p className={styles.hint}>Static official club knowledge. Notes and feedback never become knowledge automatically. Create official knowledge here or from a genuine unanswered review case. Activate explicitly and retest; resolve any linked case separately.</p>
  <button disabled={busy||Boolean(caseData)} onClick={()=>{setError('');setDetail(null);setCaseData({caseId:null,question:'',sources:[],blocked:false,managerCreated:true});}}>New Approved Answer</button>
  {error&&<p role="alert" className={styles.error}>{error}</p>}
  <section aria-label="Authority Warnings"><h3>Authority Warnings ({data.warnings.length})</h3><p className={styles.hint}>Separate from Not Helpful, Unanswered and Conflict metrics. {data.warningWindow}</p>
   {data.warnings.map((w,i)=><article key={`${w.outcomeId}:${i}`} className="my-3 rounded border border-amber-400 bg-amber-50 p-3"><strong>Authority Warning — A higher-authority official LWR source may conflict with this Approved Answer. Review required.</strong><p>{w.version} · {date(w.observedAt)} · {w.leagueScope} · {w.origin} · {w.reason.replaceAll('_',' ')}</p><button onClick={()=>open(w.approvedRevisionId)}>Review Approved Answer revision</button> <button onClick={()=>viewSource(w.chunkId)}>View governing Official Source</button></article>)}
   {!data.warnings.length&&<p>No unresolved warnings in the retained window.</p>}
  </section>
  {source&&<section className="my-3 rounded border p-4"><h3>{source.title} · Rule {source.ruleNumber} · Page {source.pageNumber}</h3><p className={styles.answer}>{source.passage}</p><button onClick={()=>setSource(null)}>Close source</button></section>}
  {caseData&&<section><h3>{caseData.managerCreated?'New Approved Answer':'Create Approved Answer — source review'}</h3><p>Source: {caseData.managerCreated?'Manager-created':'Review case'}</p><p>{caseData.question}</p>
   {caseData.managerCreated?<Editor request={api} key="manager-created" caseData={caseData} seasons={data.seasons} saved={async id=>{await load();await open(id);}}/>:<ExistingEvidenceDecision key={caseData.caseId} data={caseData} request={api} retest={retest}>{caseData.blocked?<><p role="alert">Existing official evidence or a linked item requires review before creating duplicate knowledge.</p><a href="/ai-assistant/review">Return to AI/Retrieval Review</a> <button onClick={()=>retest(caseData.question)}>Retest Question</button>{caseData.existingAnswerId&&<button onClick={()=>{const r=data.revisions.find(r=>r.answer_id===caseData.existingAnswerId);if(r)open(r.id);}}>Open linked Approved Answer</button>}</>:<Editor request={api} key={caseData.caseId||'manager-created'} caseData={caseData} seasons={data.seasons} saved={async id=>{await load();await open(id);}}/>}</ExistingEvidenceDecision>}
   <button onClick={()=>setCaseData(null)}>Close creation</button></section>}
  <div className={styles.filters}><label>Search Approved Answers<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/></label><label>League scope filter<select value={scope} onChange={e=>setScope(e.target.value)}><option value="">All scopes</option>{APPROVED_SCOPES.map(s=><option key={s}>{s}</option>)}</select></label><label>Publication status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{['draft','active','retired'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy} onClick={load}>Refresh</button></div>
  <p className={styles.hint}>Most recent 300 revisions. Times use your device timezone. Future-effective and expired revisions do not govern current answers.</p>
  <div className={styles.tableWrap}><table><thead><tr><th>Title / Revision</th><th>Status / Scope</th><th>Effective / Expires</th><th>Activated</th><th>Review</th></tr></thead><tbody>{data.revisions.filter(r=>(!status||r.status===status)&&(!scope||r.league_scope===scope)&&(!search||(r.title+' '+r.canonical_question).toLowerCase().includes(search.toLowerCase()))).map(r=><tr key={r.id}><td>{r.title}<small>Revision {r.revision_number}</small></td><td>{r.status} · {r.league_scope}{r.eligibility&&<small>{r.eligibility}</small>}</td><td>{r.effective_on} / {r.expires_on||'Standing'}</td><td>{date(r.activated_at)}</td><td><button disabled={busy} onClick={()=>open(r.id)}>View</button></td></tr>)}</tbody></table></div>
  {detail&&<RevisionDialog request={api} key={`${detail.revision.id}:${detail.revision.row_version}`} detail={detail} seasons={data.seasons} close={()=>setDetail(null)} reload={async id=>{await load();await open(id||detail.revision.id);}} retest={retest} viewSource={viewSource}/>}
 </section>;
}
function Evidence({findings=[],view}){return <div>{findings.map(s=><article key={s.selectionKey||s.chunkId}><p><strong>{s.direct?'Existing official source may already answer this question':'Review possible related official evidence'}: {s.title} · Rule {s.ruleNumber||'not retained'} · Page {s.pageNumber}</strong></p><p className={styles.answer}>{s.passage}</p><button onClick={()=>view(s.chunkId)}>View existing evidence</button></article>)}{!findings.length&&<p>No matching passage was found by the bounded source review. This does not prove that no official policy exists. Review the official material before activation.</p>}</div>;}
function Editor({caseData,revision,seasons,saved,onDirty,request=approvedApi}){
 const api=request;
 const [draft,setDraft]=useState(()=>revision?{...blank(),...revision}:{...blank(),canonical_question:caseData.question}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [overlapDistinction,setOverlapDistinction]=useState('');
 const retry=useRef(null);const [references,setReferences]=useState([]);
 const change=(k,v)=>{onDirty?.();setDraft(d=>({...d,[k]:v}));};
 async function save(e){e.preventDefault();setBusy(true);setError('');const body={action:revision?'save':'create',id:revision?.id||caseData.caseId,expected:revision?.row_version,draft,overlapDistinction,staticPolicyConfirmed:confirmed};const key=JSON.stringify(body);if(retry.current?.key!==key)retry.current={key,operation:crypto.randomUUID()};try{const r=await api({}, {...body,operation:retry.current.operation});await saved(r.revisionId);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <form onSubmit={save} className={approvedStyles.form}>{error&&<p role="alert">{error}</p>}
  {[['title','Title',160],['topic_key','Policy/topic key',80],['canonical_question','Canonical question',2400],['approved_answer','Official approved answer',6000]].map(([key,label,max])=><label key={key}>{label}{key==='approved_answer'||key==='canonical_question'?<textarea required className="w-full" maxLength={max} value={draft[key]} onChange={e=>change(key,e.target.value)}/>:<input required className="w-full" maxLength={max} value={draft[key]} onChange={e=>change(key,e.target.value)}/>}</label>)}
  <label>League scope<select value={draft.league_scope} onChange={e=>change('league_scope',e.target.value)}>{APPROVED_SCOPES.map(s=><option key={s}>{s}</option>)}</select></label>
  <label>Time scope<select value={draft.temporal_scope} onChange={e=>{onDirty?.();setDraft(d=>({...d,temporal_scope:e.target.value,season_id:null}));}}><option value="standing">Standing policy</option><option value="season">Season-specific policy/date</option></select></label>
  {draft.temporal_scope==='season'&&<label>Season<select required value={draft.season_id||''} onChange={e=>change('season_id',e.target.value)}><option value="">Choose season</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
  <label>Effective date (club calendar)<input required type="date" value={draft.effective_on} onChange={e=>change('effective_on',e.target.value)}/></label>
  <label>Expiration date — excluded from eligibility<input type="date" required={draft.temporal_scope==='season'} value={draft.expires_on||''} onChange={e=>change('expires_on',e.target.value||null)}/></label>
  <fieldset><legend>Related Official Source (optional)</legend><button type="button" onClick={async()=>{try{setReferences((await api({op:'evidence',question:draft.canonical_question})).sources);}catch(e){setError(e.message);}}}>Find related official passages</button><select aria-label="Related Official Source" value={references.find(r=>r.chunkId===draft.related_chunk_id&&r.passage===draft.related_passage)?.selectionKey||(draft.related_chunk_id?'retained':'')} onChange={e=>{const r=references.find(r=>r.selectionKey===e.target.value);onDirty?.();setDraft(d=>({...d,related_chunk_id:r?.chunkId||null,related_passage:r?.passage||null,related_rule_identity:r?.ruleNumber??null}));}}><option value="">No related source</option>{draft.related_chunk_id&&!references.some(r=>r.chunkId===draft.related_chunk_id&&r.passage===draft.related_passage)&&<option value="retained">Retained official passage — Rule {draft.related_rule_identity||'not numbered'}</option>}{references.map(r=><option key={r.selectionKey} value={r.selectionKey}>{r.title} — Rule {r.ruleNumber||'not numbered'} — Page {r.pageNumber} — {r.heading}</option>)}</select>{draft.related_passage&&<p className={styles.answer}>{draft.related_passage}</p>}</fieldset>
  <fieldset><legend>Public information links (optional)</legend>{draft.public_links.map((l,i)=><div className="grid gap-2" key={i}><label>Label<input value={l.label} onChange={e=>change('public_links',draft.public_links.map((v,j)=>j===i?{...v,label:e.target.value}:v))}/></label><label>Official public HTTPS URL<input type="url" value={l.url} onChange={e=>change('public_links',draft.public_links.map((v,j)=>j===i?{...v,url:e.target.value}:v))}/></label><button type="button" onClick={()=>change('public_links',draft.public_links.filter((_,j)=>j!==i))}>Remove link</button></div>)}{draft.public_links.length<3&&<button type="button" onClick={()=>change('public_links',[...draft.public_links,{label:'',url:''}])}>Add public link</button>}</fieldset>
  <label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed the official sources. This is static official club knowledge, not current player/team data or a workaround for a retrieval defect.</label>
  <label>Missing-policy distinction from related official evidence (required when similar sources exist)<textarea maxLength={1800} value={overlapDistinction} onChange={e=>setOverlapDistinction(e.target.value)}/></label><button disabled={busy||!confirmed} type="submit">{busy?'Saving…':'Save Draft'}</button><p className={styles.hint}>Saving does not activate, embed, retest or resolve the review case.</p>
 </form>;
}
function RevisionDialog({detail,seasons,close,reload,retest,request=approvedApi}){
 const api=request;
 const r=detail.revision,dialog=useRef(null),retry=useRef(null);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[preflight,setPreflight]=useState(null),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[overlapDistinction,setOverlapDistinction]=useState(''),[formalSource,setFormalSource]=useState(null),[dirty,setDirty]=useState(false);
 useEffect(()=>{const d=dialog.current,focus=document.activeElement;d.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d.close();document.body.style.overflow=overflow;focus?.focus();};},[]);
 async function action(action){setBusy(true);setError('');const body={action,id:r.id,expected:r.row_version,reason,overlapDistinction,token:preflight?.token,confirm:confirmed};const key=JSON.stringify(body);if(retry.current?.key!==key)retry.current={key,operation:crypto.randomUUID()};try{const result=await api({}, {...body,operation:retry.current.operation});if(action==='preflight')setPreflight(result);else await reload(result.revisionId);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className={styles.dialog} aria-labelledby="approved-title" onCancel={e=>{e.preventDefault();if(!busy)close();}}><header><h2 id="approved-title">{r.title} — Revision {r.revision_number}</h2><button onClick={close} disabled={busy}>Close</button></header>{error&&<p role="alert">{error}</p>}
  <p>Source: {detail.item.source_review_case_id?'Review case':'Manager-created'}</p>
  <p>{r.status} · {r.league_scope} · Effective {r.effective_on} · Expires {r.expires_on||'not set'}</p><p>Activated: {date(r.activated_at)} · Activated by: {detail.activatedBy} · Retired: {date(r.retired_at)}</p>
  {r.status==='draft'?<Editor request={api} revision={r} seasons={seasons} saved={reload} onDirty={()=>{setDirty(true);setPreflight(null);setConfirmed(false);}}/>:<p className={styles.answer}>{r.approved_answer}</p>}
  {detail.related&&<section><h3>Related Official Source: {detail.related.title} — Rule {detail.related.ruleNumber||'not numbered'} — Page {detail.related.pageNumber}</h3><p className={styles.answer}>{detail.related.passage}</p></section>}
  {dirty&&<p>Save Draft changes before reviewing activation.</p>}{r.status==='draft'&&<button disabled={busy||dirty} onClick={()=>action('preflight')}>Review activation</button>}
  {preflight&&<section><h3>Activation review</h3><p>{r.approved_answer}</p><p>Scope: {r.league_scope}; effective {r.effective_on}; expires {r.expires_on||'not set'}. Activation publishes this exact revision when effective.</p><Evidence findings={preflight.sources} view={async id=>{try{setFormalSource((await api({op:'source',id})).source);}catch(e){setError(e.message);}}}/>{formalSource&&<p className={styles.answer}>{formalSource.title}: {formalSource.passage}</p>}{preflight.overlaps.map(v=><p key={v.id}>Overlapping {v.status||'active'} policy: {v.title}</p>)}{preflight.blocked?<p role="alert">Activation blocked. Resolve existing authority/duplicate knowledge first.</p>:<><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Activate this official answer for players. I have reviewed its scope, dates and authority.</label><label>If a similar Active answer is identified, explain the distinct policy gap<textarea maxLength={1800} value={overlapDistinction} onChange={e=>setOverlapDistinction(e.target.value)}/></label><button disabled={busy||!confirmed} onClick={()=>action('activate')}>Activate</button></>}</section>}
  {r.status!=='draft'&&<button disabled={busy} onClick={()=>action('edit')}>Edit as New Draft</button>}
  {r.status==='active'&&<section><label>Retirement reason / incorporated official source<textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={()=>action('retire')}>Retire Approved Answer</button></section>}
  <button disabled={busy} onClick={()=>retest(r.canonical_question)}>Retest Question</button><p className={styles.hint}>Only eligible Active knowledge participates. Run the prefilled test explicitly. {detail.item.source_review_case_id?'Then resolve the linked review case separately.':'No review case is linked to this manager-created knowledge.'}</p><a href="/ai-assistant/review">Return to review cases</a>
  {detail.linkedCase&&<p><a href={`/ai-assistant/review?group=${encodeURIComponent(detail.linkedCase.group_id)}`}>Open linked review case — {detail.linkedCase.status}</a></p>}<h3>Revision history</h3>{detail.history.map(v=><p key={v.id}><button disabled={busy} onClick={()=>reload(v.id)}>Revision {v.revision_number} — {v.status}</button> · Activated {date(v.activated_at)}</p>)}
  <h3>Audit history</h3>{detail.events.map(e=><details key={e.id}><summary>{date(e.created_at)} · {e.action.replaceAll('_',' ')}{e.reason?` · ${e.reason}`:''}</summary><pre className={styles.answer}>{JSON.stringify({before:e.before_state,after:e.after_state},null,2)}</pre></details>)}
 </dialog>;
}
