"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AppHeader from "../../components/AppHeader";
import LoadingScreen from "../../components/LoadingScreen";
import { getRequestAuthorizationHeaders, requireRole } from "../../lib/auth";

const scopes = [["all", "All"], ["weekday", "Weekday"], ["primetime", "PrimeTime"], ["saturday", "Saturday"], ["lms_help", "LMS Help"]];
const contextDefaults = { currentPath: "", featureModule: "", seasonId: "", leagueId: "", divisionId: "", teamId: "", userRole: "league_manager" };

export default function TestAiAssistantPage() {
  const router = useRouter(); const [ready, setReady] = useState(false); const [question, setQuestion] = useState("How does scoring freeze work?"); const [askAbout, setAskAbout] = useState("all"); const [context, setContext] = useState(contextDefaults); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  useEffect(() => { (async () => { const user = await requireRole(router, "league_manager"); if (user) { setContext((current) => ({ ...current, userRole: user.role })); setReady(true); } })(); }, [router]);
  async function submit(event) { event.preventDefault(); setWorking(true); setError(""); try { const response = await fetch("/api/ai-assistant/retrieval", { method: "POST", headers: { "Content-Type": "application/json", ...(await getRequestAuthorizationHeaders()) }, body: JSON.stringify({ question, askAbout, context }) }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.success) throw new Error(payload.error || "Unable to retrieve official evidence."); setResult(payload.retrieval); } catch (requestError) { setError(requestError.message); } finally { setWorking(false); } }
  const field = (label, key, placeholder = "") => <label className="block text-sm font-black text-slate-800"><span className="mb-1 block">{label}</span><input value={context[key]} placeholder={placeholder} onChange={(e) => setContext((current) => ({ ...current, [key]: e.target.value }))} className={inputClass}/></label>;
  if (!ready) return <LoadingScreen subtitle="Loading Test AI Assistant..."/>;
  return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-7xl"><AppHeader title="Test AI Assistant" subtitle="Manager-only official-document retrieval diagnostics. This stage never generates an AI answer." actions={<button onClick={() => router.push("/ai-assistant")} className={secondary}>AI Source Management</button>}/>{error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">{error}</div>}<section className="rounded-2xl bg-white p-4 shadow"><form onSubmit={submit} className="grid gap-3"><label className="text-sm font-black text-slate-800">Question<textarea value={question} maxLength={1000} onChange={(e) => setQuestion(e.target.value)} className={`${inputClass} mt-1 min-h-24`} required/></label><div className="grid gap-3 md:grid-cols-3"><label className="text-sm font-black text-slate-800">Ask About<select value={askAbout} onChange={(e) => setAskAbout(e.target.value)} className={inputClass}>{scopes.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>{field("Current page/path", "currentPath", "/match-setup")}{field("Page/module", "featureModule", "Match Setup")}</div><details className="rounded-xl border border-slate-200 bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-black">Optional context</summary><div className="mt-3 grid gap-3 md:grid-cols-3">{field("Season ID", "seasonId", "UUID")}{field("League ID", "leagueId", "UUID")}{field("Division ID", "divisionId", "UUID")}{field("Team ID", "teamId", "UUID")}</div></details><button disabled={working} className={primary}>{working ? "Retrieving..." : "Test Retrieval"}</button></form></section>{result && <Diagnostics result={result}/>}</div></main>;
}

function Diagnostics({ result }) { const evidence = result.evidence; return <div className="mt-5 grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><section className="space-y-5"><Panel title="Request"><pre className="overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(result.request, null, 2)}</pre></Panel><Panel title="Retrieval environment"><p className="text-sm font-semibold">{result.environment.embeddingModel} · {result.environment.embeddingDimensions} dimensions · threshold {f(result.environment.evidenceThreshold)} · limit {result.environment.retrievalLimit}</p><p className="mt-2 text-xs font-bold text-slate-600">Embedding {result.metrics.embeddingMs}ms ({result.metrics.embeddingInputTokens ?? "tokens unavailable"}) · database {result.metrics.retrievalMs}ms · total {result.metrics.totalMs}ms</p></Panel><Panel title="Evidence sufficiency"><div className={`rounded-xl p-3 text-sm font-black ${evidence.sufficient ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}>Evidence sufficient: {evidence.sufficient ? "YES" : "NO"}<p className="mt-2 text-xs font-semibold">{evidence.stage4Fallback}</p></div></Panel><Panel title="Documents considered">{result.documentsConsidered.map((d) => <div key={d.id} className="mb-2 rounded-lg bg-slate-50 p-2 text-xs font-semibold"><b>{d.title}</b><br/>{d.type} · authority {d.authorityRank} · {d.applicability} · active {d.activeVersionLabel}</div>)}</Panel><Panel title="Conflict diagnostic"><p className="text-sm font-semibold">Potential source conflict: {result.conflict.potentialConflict ? "YES" : "NO"}</p><p className="mt-1 text-xs text-slate-600">{result.conflict.limitation}</p></Panel></section><section className="space-y-5"><Panel title={`Supplied future-model evidence (${result.suppliedEvidence.length})`}><Chunks chunks={result.suppliedEvidence}/></Panel><Panel title={`All ranked candidates (${result.candidates.length})`}><Chunks chunks={result.candidates}/></Panel></section></div>; }
function Chunks({ chunks }) { return chunks.length ? <div className="space-y-3">{chunks.map((c,index) => <article key={c.chunkId} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-2"><b>#{index+1} {c.documentTitle}</b><span className="font-black text-blue-700">{f(c.combinedScore)}</span></div><div className="mt-1 text-xs font-bold text-slate-500">Page {c.pageNumber || "-"} · {c.sectionLabel || c.heading || "No section"}{c.ruleNumber ? ` · Rule ${c.ruleNumber}` : ""} · searchable yes</div><div className="mt-2 grid grid-cols-2 gap-1 text-xs font-semibold text-slate-600 sm:grid-cols-5"><span>Semantic {f(c.semanticScore)}</span><span>Keyword {f(c.keywordScore)}</span><span>Exact {f(c.exactScore)}</span><span>Authority {f(c.authorityScore)}</span><span>Context {f(c.contextScore)}</span></div><div className="mt-2 rounded-lg bg-slate-50 p-2 text-xs font-semibold text-slate-700"><p><b>Exact match reason:</b> {c.exactMatchReason || "None"}</p><p className="mt-1"><b>FTS:</b> {c.ftsDiagnostic?.matched ? "Matched" : "No match"}{c.ftsDiagnostic?.candidateRank ? ` · keyword candidate #${c.ftsDiagnostic.candidateRank}` : ""} · normalized terms: {c.ftsDiagnostic?.normalizedTerms?.join(" + ") || "none"}{c.ftsDiagnostic?.retrievalExpansion?.length ? ` · retrieval expansion: ${c.ftsDiagnostic.retrievalExpansion.join(" + ")}` : ""}</p><p className="mt-1"><b>Detected intent:</b> {c.intentDiagnostic?.detectedIntent || "None"} · <b>Intent evidence match:</b> {c.intentDiagnostic?.evidenceMatch || "None"}</p></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{c.content}</p></article>)}</div> : <p className="text-sm text-slate-500">No eligible official evidence.</p>; }
const inputClass="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-semibold"; const primary="w-fit rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300"; const secondary="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-black"; function Panel({title,children}) { return <section className="rounded-2xl bg-white p-4 shadow"><h2 className="text-lg font-black">{title}</h2><div className="mt-3">{children}</div></section>; } function f(value) { return Number.isFinite(Number(value)) ? Number(value).toFixed(3) : "—"; }
