'use client';
import {Fragment,useCallback,useEffect,useRef,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import AppHeader from './AppHeader';
import SystemFooter from './SystemFooter';
import {setViewAsPageState,hydrateViewAsImages} from '../lib/viewAsPageState.js';
import {defaultDashboardForRole} from '../lib/permissions';
const STORE='lwr-view-context-v1';
const supported=new Set(['/player-dashboard','/captain-dashboard','/ask-lwr','/standings']);
export default function ViewAsSharedPages({children}){
 const path=usePathname(),router=useRouter();
 const [viewer,setViewer]=useState(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const context=useRef(null),normal=useRef(null),returnPath=useRef('/'),epoch=useRef(0),banner=useRef(null),projection=useRef(null),refreshSequence=useRef(0);
 const invalidatePending=useCallback(()=>{refreshSequence.current++;},[]);
 const purge=useCallback(message=>{epoch.current++;context.current=null;sessionStorage.removeItem(STORE);setViewAsPageState(null);setViewer(null);setReady(false);setError(message);},[]);
 const request=useCallback(async body=>{if(!context.current)throw new Error('Start View As User from Member Detail in your normal LMS tab.');const response=await fetch('/api/view-as/read',{method:'POST',headers:{'Content-Type':'application/json','x-view-as-context':context.current},body:JSON.stringify(body),cache:'no-store'});if(!response.ok){const data=await response.json().catch(()=>({}));if(response.status===401||response.status===403)purge(data.error||'View As User expired.');throw new Error(data.error||'View As User unavailable.');}return response;},[purge]);
 const refresh=useCallback(async(conceal=true)=>{const stamp=epoch.current,sequence=++refreshSequence.current;if(conceal)setReady(false);try{const status=await(await request({operation:'status'})).json();const page=await(await request({operation:'page',contract:'dashboard',args:{}})).json();await hydrateViewAsImages(page,request);if(stamp!==epoch.current||sequence!==refreshSequence.current)return;const effective={...status.viewer,...page.viewer,publishedMatchIds:page.tables.matches.map(m=>m.id)};returnPath.current=effective.returnPath;const signature=JSON.stringify(page);if(projection.current!==signature){projection.current=signature;setRevision(n=>n+1);}setViewAsPageState({viewer:effective,tables:page.tables,request});setViewer(effective);setError('');setReady(true);}catch(e){if(stamp!==epoch.current||sequence!==refreshSequence.current)return;setViewAsPageState(null);setReady(false);setError(e.message);}},[request]);
 useEffect(()=>{let disposed=false,exchanging=false;const opener=window.opener;
  const exchange=async event=>{if(disposed||exchanging||event.source!==opener||!normal.current||event.origin!==normal.current||event.data?.type!=='lwr-view-handoff')return;exchanging=true;try{const response=await fetch('/api/view-as/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:event.data.code})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Handoff failed.');context.current=data.context;sessionStorage.setItem(STORE,data.context);window.opener=null;await refresh();}catch(e){purge(e.message);}};
  window.addEventListener('message',exchange);
  fetch('/api/view-as/bootstrap',{method:'POST'}).then(r=>{if(!r.ok)throw new Error('View As User is unavailable.');return r.json();}).then(data=>{if(disposed)return;normal.current=data.normalOrigin;context.current=sessionStorage.getItem(STORE);if(context.current)refresh();else if(opener)opener.postMessage({type:'lwr-view-ready',challenge:data.challenge},data.normalOrigin);else setError('Start View As User from Member Detail in your normal LMS tab.');}).catch(e=>{if(!disposed)setError(e.message);});
  const validate=()=>{if(context.current)refresh();};const visibility=()=>{if(document.hidden)setReady(false);else validate();};window.addEventListener('pageshow',validate);window.addEventListener('focus',validate);document.addEventListener('visibilitychange',visibility);const timer=setInterval(()=>{if(context.current&&!document.hidden)refresh(false);},30000);
  return()=>{disposed=true;invalidatePending();clearInterval(timer);window.removeEventListener('message',exchange);window.removeEventListener('pageshow',validate);window.removeEventListener('focus',validate);document.removeEventListener('visibilitychange',visibility);setViewAsPageState(null);};
 },[purge,refresh,invalidatePending]);
 useEffect(()=>{if(!viewer)return;const timer=setTimeout(()=>purge('View As User session expired.'),Math.max(0,new Date(viewer.expires)-Date.now()));return()=>clearTimeout(timer);},[viewer,purge]);
 useEffect(()=>{if(ready&&(path==='/view-as'||(path==='/'&&defaultDashboardForRole(viewer.role)!=='/')))router.replace(defaultDashboardForRole(viewer.role));},[ready,path,router,viewer]);
 useEffect(()=>{if(!banner.current)return;const observer=new ResizeObserver(()=>{document.body.style.paddingBottom=`${banner.current?.offsetHeight||0}px`;document.body.style.setProperty('--view-as-banner-height',`${banner.current?.offsetHeight||0}px`);});observer.observe(banner.current);return()=>{observer.disconnect();document.body.style.paddingBottom='';document.body.style.removeProperty('--view-as-banner-height');};},[]);
 async function exit(){try{await request({operation:'exit'});purge('View As User ended.');if(normal.current)window.location.assign(normal.current+returnPath.current);}catch(e){setError(e.message);}}
 const allowed=(supported.has(path)||/^\/help\/(player|captain|club-pro|league-manager|commissioner)$/.test(path)||(path.startsWith("/live-match/")&&viewer?.publishedMatchIds?.includes(path.split("/")[2]))||/^\/(official-document|approved-answer)\/[^/]+$/.test(path)||(path.startsWith('/teams/')&&viewer?.managed?.includes(path.split('/')[2])))&&(path!=='/captain-dashboard'||viewer?.role!=='player');
 return <><style>{`html[data-lms-view-as="true"] nav[aria-label^="Mobile"],html[data-lms-view-as="true"] .system-footer{bottom:var(--view-as-banner-height,0px)}`}</style><aside ref={banner} aria-label="View As User status" className="fixed inset-x-0 bottom-0 z-[11000] border-t-4 border-amber-400 bg-slate-950 p-3 text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-2"><div><strong>VIEWING AS: {viewer?.targetName||(error?'Access unavailable':'Validating…')} · READ-ONLY</strong>{viewer&&<p className="text-xs">{viewer.roles?.length ? viewer.roles.join(', ').replaceAll('_',' ') : viewer.role === 'player' ? 'Player' : viewer.role?.replaceAll('_',' ')} · Signed in as {viewer.actorName} ({viewer.actorRole?.replaceAll('_',' ')})</p>}</div>{viewer&&<button type="button" onClick={exit} className="min-h-11 rounded-xl border border-white px-4 py-2 font-semibold focus-visible:outline-2 focus-visible:outline-amber-300">Exit View As User</button>}</div></aside>{error&&<p role="alert" className="m-4 rounded border border-red-300 p-4">{error}</p>}{!ready?(error?null:<p role="status" className="p-6">Validating read-only access…</p>):allowed?<Fragment key={revision}>{children}</Fragment>:<main className="min-h-screen bg-slate-100 p-6"><AppHeader title="League Management"/><h1 className="text-xl font-semibold">This page isn&apos;t currently available in View As mode.</h1></main>}{ready&&<SystemFooter/>}</>;
}
