-- Mark copies independently of the schedule's draft/generated state.
alter table public.league_schedule_settings
  add column if not exists is_copy boolean not null default false;

-- Associate newly generated byes with their schedule setting. Existing byes
-- stay unassigned so their current league/division behavior is preserved.
alter table public.team_byes
  add column if not exists schedule_setting_id uuid;

alter table public.team_byes
  add constraint team_byes_schedule_setting_id_fkey
  foreign key (schedule_setting_id)
  references public.league_schedule_settings(id)
  on delete set null;

create index if not exists team_byes_schedule_setting_id_idx
  on public.team_byes (schedule_setting_id);
